### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by malcolmgarner-movement** [rahulbaburaj/body2body#2]
Tried to run train.py with python3 on my macbook pro (os mojave) and got this error:
**Command**

$ python3 train.py --dataroot ./datasets/dance_mimic --name dance_mimic_pix2pix --model pix2pix --which_model_netG unet_256 

**Response**

Traceback (most recent call last):
  File "train.py", line 7, in <module>
    opt = TrainOptions().parse()
  File "/Users/Malcom/Desktop/Projects/body2body/options/base_options.py", line 60, in parse
    torch.cuda.set_device(self.opt.gpu_ids[0])
  File "/Users/Malcom/miniconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 265, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
---------------------------------------------------------

I saw the error on a similar issue and tried their solution but that didn't help either. Issue linked here: https://github.com/KupynOrest/DeblurGAN/issues/74

unsure how to proceed with this.

**Comment by oyoycr** [comment]
add --gpu_ids -1 to your python command.  It worked for me.
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/360

**Comment by RoyceDavison** [comment]
An example will be like (suppose I want to apply a pre-trained model): 
`python ./test.py --dataroot ./datasets/monet2photo/testA/ --name monet2photo_pretrained --model test --no_dropout --gpu_ids -1` 
Just add --gpu_ids -1 to your python command.
