### ISSUE TITLE
cannot import name 'np' from 'torch' 

### ISSUE THREAD

**Issue by Sepideh-Rezaeirad** [rahulbaburaj/body2body#3]
Hi there,

when I run 'picture_cpu_demo' file I faced with this error
could anyone help me?
I installed the latest version from torch
Is the error related this? if it is, which version is proper.

Thanks

**Comment by farzadmohseni-ir** [comment]
@Sepideh-Rezaeirad 


> Hi there,
> 
> when I run 'picture_cpu_demo' file I faced with this error
> could anyone help me?
> I installed the latest version from torch
> Is the error related this? if it is, which version is proper.
> 
> Thanks

**Were you able to fix this error ?**
